# Generated by Django 6.0.1 on 2026-02-17 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='bpm',
            field=models.IntegerField(default=120, help_text='Beats per minute'),
        ),
        migrations.AddField(
            model_name='project',
            name='key',
            field=models.CharField(default='C', help_text='Musical key (e.g., C, Dm, Am)', max_length=10),
        ),
    ]
