# Generated by Django 6.0.1 on 2026-03-18 20:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_project_bpm_project_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='bars',
            field=models.IntegerField(default=4, help_text='Project length in bars (1 bar = 4 beats). Range: 1–8.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)]),
        ),
        migrations.AlterField(
            model_name='project',
            name='bpm',
            field=models.IntegerField(default=120, help_text='Beats per minute (40–200)', validators=[django.core.validators.MinValueValidator(40), django.core.validators.MaxValueValidator(200)]),
        ),
    ]
