# Generated by Django 6.0.1 on 2026-03-24 01:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_project_bars_choices_4_to_16'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='bpm',
            field=models.IntegerField(default=120, help_text='Beats per minute (40-200)', validators=[django.core.validators.MinValueValidator(40), django.core.validators.MaxValueValidator(200)]),
        ),
    ]
